image: php:7.1

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - apt-get update && apt-get install -y unzip zlib1g-dev
          - docker-php-ext-install zip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          - vendor/bin/phpcs --standard=PSR2 src/
          - vendor/bin/phpcpd src
          - vendor/bin/phpstan analyse -l 7 src tests
          - php bin/phpunit