version: '2'

services:
    data:
        image: busybox
        container_name: project_data
        volumes:
            - "../:/var/www/html"

    server:
        build: nginx
        container_name: project_server
        ports:
            - "81:80"
        volumes_from:
            - data
        links:
            - php

    php:
        build: php
        container_name: project_php
        volumes_from:
            - data

    database:
        image: mariadb:latest
        container_name: project_database
        ports:
            - "3308:3306"
        env_file: .env
        volumes_from:
            - data